export const englishWords = [
    'a1:accident:ss',
    'a1:activity:ss',
    'a1:actor:ss',
    'a1:addition:ss',
    'a1:administration:ss',
    'a1:advertising:ss',
    'a1:advice:aa',
    'a1:affair:aa',
    'a1:agency:aa',
    'a1:agreement:aa',
    'a1:airport:aa',
    'a1:alcohol:aa',
    'a1:ambition:vv',
    'a1:analysis:vv',
    'a1:analyst:vv',
    'a1:anxiety:vv',
    'a1:appearance:vv',
    'a2:apple:ss',
    'a2:application:ss',
    'a2:appointment:ss',
    'a2:area:ss',
    'a2:argument:ss',
    'a2:army:ss',
    'a2:arrival:aa',
    'a2:article:aa',
    'a2:artisan:aa',
    'a2:aspect:aa',
    'a2:assignment:aa',
    'a2:assistance:aa',
    'a2:assistant:vv',
    'a2:association:vv',
    'a2:assumption:vv',
    'a2:atmosphere:vv',
    'a2:attention:vv',
    'a2:attitude:vv',
    'a2:audience:vv',
    'a2:awareness:vv',
    'b1:beer:ss',
    'b1:birthday:ss',
    'b1:bath:ss',
    'b1:bread:ss',
    'b1:baseball:ss',
    'b1:blood:ss',
    'b1:breath:ss',
    'b1:buyer:ss',
    'b1:bird:ss',
    'b1:bedroom:ss',
    'b1:basket:ss',
    'b1:boyfriend:ss',
    'b1:bathroom:ss',
    'b1:criticism:ss',
    'b1:contract:ss',
    'b1:championship:ss',
    'b1:customer:aa',
    'b1:contribution:aa',
    'b1:committee:aa',
    'b1:category:aa',
    'b1:camera:aa',
    'b1:context:aa',
    'b1:chest:aa',
    'b1:cancer:aa',
    'b1:complaint:aa',
    'b1:candidate:aa',
    'b1:combination:aa',
    'b1:connection:vv',
    'b1:community:vv',
    'b1:currency:vv',
    'b1:competition:vv',
    'b1:chemistry:vv',
    'b1:construction:vv',
    'b1:control:vv',
    'b1:cookie:vv',
    'b1:classroom:vv',
    'b1:cabinet:vv',
    'b1:comparison:vv',
    'b2:church:ss',
    'b2:communication:ss',
    'b2:climate:ss',
    'b2:confusion:ss',
    'b2:child:ss',
    'b2:collection:ss',
    'b2:country:ss',
    'b2:courage:ss',
    'b2:charity:ss',
    'b2:concept:ss',
    'b2:computer:vv',
    'b2:city:vv',
    'b2:conclusion:vv',
    'b2:cousin:vv',
    'b2:conversation:vv',
    'b2:consequence:vv',
    'b2:cell:vv',
    'b2:chocolate:vv',
    'b2:coffee:vv',
    'b2:cheek:aa',
    'b2:clothes:aa',
    'b2:county:aa',
    'b2:celebration:aa',
    'b2:chapter:aa',
    'b2:difference:aa',
    'b2:definition:aa',
    'b2:difficulty:aa',
    'b2:disk:aa',
    'c1:direction:ss',
    'c1:debt:ss',
    'c1:department:ss',
    'c1:depth:ss',
    'c1:dinner:ss',
    'c1:drama:ss',
    'c1:department:ss',
    'c1:drawing:ss',
    'c1:depression:ss',
    'c1:drawer:ss',
    'c1:desk:ss',
    'c1:dirt:ss',
    'c1:description:ss',
    'c1:distribution:ss',
    'c1:device:ss',
    'c1:data:ss',
    'c1:discussion:ss',
    'c1:delivery:ss',
    'c1:disaster:ss',
    'c1:disease:ss',
    'c1:dealer:ss',
    'c1:driver:ss',
    'c1:departure:aa',
    'c1:development:aa',
    'c1:diamond:aa',
    'c1:director:aa',
    'c1:death:aa',
    'c1:decision:aa',
    'c1:education:aa',
    'c1:estate:aa',
    'c1:enthusiasm:aa',
    'c1:election:aa',
    'c1:error:aa',
    'c1:entry:vv',
    'c1:establishment:vv',
    'c1:excitement:vv',
    'c1:examination:vv',
    'c1:effort:vv',
    'c1:emotion:vv',
    'c1:elevator:vv',
    'c1:event:vv',
    'c1:employee:vv',
    'c1:exam:vv',
    'c1:emphasis:vv',
    'c1:expression:vv',
    'c2:engine:ss',
    'c2:employer:ss',
    'c2:editor:ss',
    'c2:efficiency:ss',
    'c2:explanation:ss',
    'c2:equipment:ss',
    'c2:engineering:ss',
    'c2:environment:ss',
    'c2:extent:ss',
    'c2:employment:ss',
    'c2:energy:ss',
    'c2:entertainment:ss',
    'c2:failure:ss',
    'c2:friendship:ss',
    'c2:football:ss',
    'c2:family:ss',
    'c2:fact:ss',
    'c2:feedback:ss',
    'c2:farmer:ss',
    'c2:food:ss',
    'c2:foundation:ss',
    'c2:freedom:aa',
    'c2:fishing:aa',
    'c2:funeral:aa',
    'c2:finding:aa',
    'c2:flight:aa',
    'c2:fortune:aa',
    'c2:garbage:aa',
    'c2:girlfriend:aa',
    'c2:government:aa',
    'c2:gene:aa',
    'c2:guidance:aa',
    'c2:guitar:aa',
    'c2:girl:aa',
    'c2:gate:aa',
    'c2:grandmother:aa',
    'c2:goal:aa',
    'c2:growth:aa',
    'c2:guest:aa',
    'c2:hearing:vv',
    'c2:hospital:vv',
    'c2:history:vv',
    'c2:health:vv',
    'c2:historian:vv',
    'c2:homework:vv',
    'c2:heart:vv',
    'c2:hotel:vv',
    'c2:hair:vv',
    'c2:highway:vv',
    'c2:height:vv',
    'c2:honey:vv',
    'c2:hall:vv',
    'c2:income:vv',
    'c2:improvement:vv',
    'c2:importance:vv',
    // 'interaction',
    // 'indication',
    // 'information',
    // 'inspection',
    // 'inflation',
    // 'impression',
    // 'instance',
    // 'inspector',
    // 'introduction',
    // 'insurance',
    // 'initiative',
    // 'industry',
    // 'imagination',
    // 'intention',
    // 'independence',
    // 'insect',
    // 'investment',
    // 'injury',
    // 'idea',
    // 'instruction',
    // 'judgment',
    // 'king',
    // 'knowledge',
    // 'length',
    // 'loss',
    // 'leadership',
    // 'literature',
    // 'location',
    // 'lake',
    // 'lady',
    // 'love',
    // 'library',
    // 'ladder',
    // 'leader',
    // 'language',
    // 'music',
    // 'marriage',
    // 'message',
    // 'method',
    // 'measurement',
    // 'mood',
    // 'mode',
    // 'maintenance',
    // 'math',
    // 'management',
    // 'manager',
    // 'meaning',
    // 'membership',
    // 'moment',
    // 'marketing',
    // 'member',
    // 'mixture',
    // 'medicine',
    // 'meat',
    // 'manufacturer',
    // 'memory',
    // 'magazine',
    // 'movie',
    // 'meal',
    // 'menu',
    // 'month',
    // 'midnight',
    // 'nature',
    // 'negotiation',
    // 'news',
    // 'night',
    // 'newspaper',
    // 'nation',
    // 'opinion',
    // 'orange',
    // 'operation',
    // 'outcome',
    // 'office',
    // 'organization',
    // 'opportunity',
    // 'obligation',
    // 'oven',
    // 'owner',
    // 'permission',
    // 'poet',
    // 'poetry',
    // 'preference',
    // 'painting',
    // 'player',
    // 'product',
    // 'power',
    // 'penalty',
    // 'percentage',
    // 'possibility',
    // 'philosophy',
    // 'property',
    // 'president',
    // 'payment',
    // 'problem',
    // 'possession',
    // 'physics',
    // 'person',
    // 'people',
    // 'profession',
    // 'presence',
    // 'policy',
    // 'police',
    // 'patience',
    // 'proposal',
    // 'psychology',
    // 'pizza',
    // 'photo',
    // 'passenger',
    // 'preparation',
    // 'piano',
    // 'performance',
    // 'procedure',
    // 'potato',
    // 'presentation',
    // 'passion',
    // 'priority',
    // 'protection',
    // 'personality',
    // 'pollution',
    // 'platform',
    // 'population',
    // 'poem',
    // 'professor',
    // 'paper',
    // 'promotion',
    // 'perception',
    // 'perspective',
    // 'quality',
    // 'quantity',
    // 'queen',
    // 'refrigerator',
    // 'recommendation',
    // 'republic',
    // 'revenue',
    // 'reading',
    // 'river',
    // 'reality',
    // 'restaurant',
    // 'reception',
    // 'replacement',
    // 'region',
    // 'role',
    // 'requirement',
    // 'revolution',
    // 'resource',
    // 'relationship',
    // 'reputation',
    // 'road',
    // 'recipe',
    // 'reflection',
    // 'responsibility',
    // 'recording',
    // 'reaction',
    // 'resolution',
    // 'response',
    // 'recognition',
    // 'series',
    // 'salad',
    // 'session',
    // 'sister',
    // 'student',
    // 'supermarket',
    // 'safety',
    // 'soup',
    // 'satisfaction',
    // 'situation',
    // 'society',
    // 'significance',
    // 'skill',
    // 'secretary',
    // 'speaker',
    // 'shirt',
    // 'stranger',
    // 'solution',
    // 'scene',
    // 'shopping',
    // 'system',
    // 'sample',
    // 'singer',
    // 'science',
    // 'storage',
    // 'signature',
    // 'suggestion',
    // 'speech',
    // 'sympathy',
    // 'selection',
    // 'studio',
    // 'song',
    // 'statement',
    // 'sector',
    // 'surgery',
    // 'story',
    // 'setting',
    // 'success',
    // 'steak',
    // 'strategy',
    // 'thing',
    // 'transport',
    // 'topic',
    // 'theory',
    // 'truth',
    // 'television',
    // 'teacher',
    // 'technology',
    // 'tension',
    // 'tennis',
    // 'tongue',
    // 'temperature',
    // 'thanks',
    // 'tale',
    // 'town',
    // 'tooth',
    // 'thought',
    // 'throat',
    // 'tradition',
    // 'trainer',
    // 'teaching',
    // 'wife',
    // 'worker',
    // 'week',
    // 'woman',
    // 'winner',
    // 'weakness',
    // 'wealth',
    // 'writing',
    // 'warning',
    // 'wedding',
    // 'world',
    // 'wood',
    // 'writer',
    // 'year',
    // 'youth',
];