export const spanishWords = [
    'a1:accidente:ss',
    'a1:actividad:ss',
    'a1:actor:ss',
    'a1:adicion:ss',
    'a1:administracion:ss',
    'a1:publicidad:ss',
    'a1:consejo:aa',
    'a1:asunto:aa',
    'a1:agencia:aa',
    'a1:acuerdo:aa',
    'a1:aeropuerto:aa',
    'a1:alcohol:aa',
    'a1:ambicion:vv',
    'a1:análisis:vv',
    'a1:analista:vv',
    'a1:ansiedad:vv',
    'a1:apariencia:vv',
    'a2:manzana:ss',
    'a2:aplicacion:ss',
    'a2:cita:ss',
    'a2:area:ss',
    'a2:argumento:ss',
    'a2:ejercito:ss',
    'a2:llegada:aa',
    'a2:articulo:aa',
    'a2:artesano:aa',
    'a2:aspecto:aa',
    'a2:asignacion:aa',
    'a2:asistencia:aa',
    'a2:asistente:vv',
    'a2:asociacion:vv',
    'a2:suposicion:vv',
    'a2:atmosfera:vv',
    'a2:atencion:vv',
    'a2:actitud:vv',
    'a2:audiencia:vv',
    'a2:conciencia:vv',
    'b1:cerveza:ss',
    'b1:cumpleaños:ss',
    'b1:baño:ss',
    'b1:pan:ss',
    'b1:beisbol:ss',
    'b1:sangre:ss',
    'b1:aliento:ss',
    'b1:comprador:ss',
    'b1:pajaro:ss',
    'b1:dormitorio:ss',
    'b1:cesta:ss',
    'b1:novio:ss',
    'b1:baño:ss',
    'b1:critica:ss',
    'b1:contrato:ss',
    'b1:campeonato:ss',
    'b1:cliente:aa',
    'b1:contribucion:aa',
    'b1:comite:aa',
    'b1:categoria:aa',
    'b1:camara:aa',
    'b1:contexto:aa',
    'b1:cofre:aa',
    'b1:cancer:aa',
    'b1:queja:aa',
    'b1:candidato:aa',
    'b1:combinacion:aa',
    'b1:conexion:vv',
    'b1:comunidad:vv',
    'b1:divisa:vv',
    'b1:competencia:vv',
    'b1:quimica:vv',
    'b1:construccion:vv',
    'b1:control:vv',
    'b1:galleta:vv',
    'b1:aula:vv',
    'b1:gabinete:vv',
    'b1:comparacion:vv',
    'b2:iglesia:ss',
    'b2:comunicacion:ss',
    'b2:clima:ss',
    'b2:confusion:ss',
    'b2:niño:ss',
    'b2:recopilacion:ss',
    'b2:pais:ss',
    'b2:coraje:ss',
    'b2:caridad:ss',
    'b2:concepto:ss',
    'b2:computadora:vv',
    'b2:ciudad:vv',
    'b2:conclusion:vv',
    'b2:primo:vv',
    'b2:conversacion:vv',
    'b2:consecuencia:vv',
    'b2:celula:vv',
    'b2:chocolate:vv',
    'b2:cafe:vv',
    'b2:mejilla:aa',
    'b2:ropa:aa',
    'b2:condado:aa',
    'b2:celebracion:aa',
    'b2:capitulo:aa',
    'b2:diferencia:aa',
    'b2:definicion:aa',
    'b2:dificultad:aa',
    'b2:disco:aa',
    'c1:direccion:ss',
    'c1:deuda:ss',
    'c1:departamento:ss',
    'c1:profundidad:ss',
    'c1:cena:ss',
    'c1:drama:ss',
    'c1:departamento:ss',
    'c1:dibujo:ss',
    'c1:depresion:ss',
    'c1:cajon:ss',
    'c1:escritorio:ss',
    'c1:suciedad:ss',
    'c1:descripcion:ss',
    'c1:distribucion:ss',
    'c1:dispositivo:ss',
    'c1:datos:ss',
    'c1:discusion:ss',
    'c1:entrega:ss',
    'c1:desastre:ss',
    'c1:enfermedad:ss',
    'c1:distribuidor:ss',
    'c1:conductor:ss',
    'c1:partida:aa',
    'c1:desarrollo:aa',
    'c1:diamante:aa',
    'c1:director:aa',
    'c1:muerte:aa',
    'c1:decision:aa',
    'c1:educacion:aa',
    'c1:bienes:aa',
    'c1:entusiasmo:aa',
    'c1:eleccion:aa',
    'c1:error:aa',
    'c1:entrada:vv',
    'c1:establecimiento:vv',
    'c1:excitacion:vv',
    'c1:examinacion:vv',
    'c1:esfuerzo:vv',
    'c1:emocion:vv',
    'c1:ascensor:vv',
    'c1:evento:vv',
    'c1:empleado:vv',
    'c1:examen:vv',
    'c1:enfasis:vv',
    'c1:expresion:vv',
    'c2:motor:ss',
    'c2:empleador:ss',
    'c2:editor:ss',
    'c2:eficiencia:ss',
    'c2:explicacion:ss',
    'c2:equipo:ss',
    'c2:ingenieria:ss',
    'c2:entorno:ss',
    'c2:medida:ss',
    'c2:empleo:ss',
    'c2:energia:ss',
    'c2:entretenimiento:ss',
    'c2:falla:ss',
    'c2:amistad:ss',
    'c2:futbol:ss',
    'c2:familia:ss',
    'c2:hecho:ss',
    'c2:retroalimentacion:ss',
    'c2:agricultor:ss',
    'c2:alimento:ss',
    'c2:fundacion:ss',
    'c2:libertad:aa',
    'c2:pesca:aa',
    'c2:funeral:aa',
    'c2:hallazgo:aa',
    'c2:vuelo:aa',
    'c2:fortuna:aa',
    'c2:basura:aa',
    'c2:novia:aa',
    'c2:gobierno:aa',
    'c2:gen:aa',
    'c2:guia:aa',
    'c2:guitarra:aa',
    'c2:chica:aa',
    'c2:porton:aa',
    'c2:abuela:aa',
    'c2:meta:aa',
    'c2:crecimiento:aa',
    'c2:invitado:aa',
    'c2:audiencia:vv',
    'c2:hospital:vv',
    'c2:historia:vv',
    'c2:salud:vv',
    'c2:historiador:vv',
    'c2:tarea:vv',
    'c2:corazon:vv',
    'c2:hotel:vv',
    'c2:cabello:vv',
    'c2:autopista:vv',
    'c2:altura:vv',
    'c2:miel:vv',
    'c2:sala:vv',
    'c2:ingreso:vv',
    'c2:mejora:vv',
    'c2:importancia:vv',
    // 'interacción',
    // 'indicacion',
    // 'informacion',
    // 'inspeccion',
    // 'inflacion',
    // 'impresion',
    // 'instancia',
    // 'inspector',
    // 'introduccion',
    // 'seguro',
    // 'iniciativa',
    // 'industria',
    // 'imaginacion',
    // 'intencion',
    // 'independencia',
    // 'insecto',
    // 'inversion',
    // 'lesion',
    // 'idea',
    // 'instruccion',
    // 'juicio',
    // 'rey',
    // 'conocimiento',
    // 'longitud',
    // 'perdida',
    // 'liderazgo',
    // 'literatura',
    // 'ubicacion',
    // 'lago',
    // 'dama',
    // 'amor',
    // 'biblioteca',
    // 'escalera',
    // 'lider',
    // 'idioma',
    // 'musica',
    // 'casamiento',
    // 'mensaje',
    // 'metodo',
    // 'medicion',
    // 'animo',
    // 'modo',
    // 'mantenimiento',
    // 'matematicas',
    // 'gestion',
    // 'gerente',
    // 'significado',
    // 'membresia',
    // 'momento',
    // 'mercadeo',
    // 'miembro',
    // 'mezcla',
    // 'medicamento',
    // 'carne',
    // 'fabricante',
    // 'memoria',
    // 'revista',
    // 'pelicula',
    // 'comida',
    // 'menu',
    // 'mes',
    // 'medianoche',
    // 'naturaleza',
    // 'negociacion',
    // 'noticias',
    // 'noche',
    // 'periodico',
    // 'nacion',
    // 'opinion',
    // 'naranja',
    // 'operacion',
    // 'desenlace',
    // 'oficina',
    // 'organizacion',
    // 'oportunidad',
    // 'obligacion',
    // 'horno',
    // 'dueño',
    // 'permiso',
    // 'poeta',
    // 'poesia',
    // 'preferencia',
    // 'cuadro',
    // 'jugador',
    // 'producto',
    // 'poder',
    // 'multa',
    // 'porcentaje',
    // 'posibilidad',
    // 'filosofia',
    // 'propiedad',
    // 'presidente',
    // 'pago',
    // 'problema',
    // 'posesion',
    // 'fisica',
    // 'persona',
    // 'gente',
    // 'profesion',
    // 'presencia',
    // 'politica',
    // 'policia',
    // 'paciencia',
    // 'propuesta',
    // 'psicologia',
    // 'pizza',
    // 'foto',
    // 'pasajero',
    // 'preparacion',
    // 'piano',
    // 'actuacion',
    // 'procedimiento',
    // 'papa',
    // 'presentacion',
    // 'pasion',
    // 'prioridad',
    // 'proteccion',
    // 'personalidad',
    // 'contaminacion',
    // 'plataforma',
    // 'poblacion',
    // 'poema',
    // 'profesor',
    // 'papel',
    // 'promocion',
    // 'percepcion',
    // 'perspectiva',
    // 'calidad',
    // 'cantidad',
    // 'reina',
    // 'refrigerador',
    // 'recomendacion',
    // 'republica',
    // 'ganancia',
    // 'lectura',
    // 'rio',
    // 'realidad',
    // 'restaurante',
    // 'recepcion',
    // 'reemplazo',
    // 'region',
    // 'rol',
    // 'requisito',
    // 'revolucion',
    // 'recurso',
    // 'relacion',
    // 'reputacion',
    // 'carretera',
    // 'receta',
    // 'reflexion',
    // 'responsabilidad',
    // 'grabacion',
    // 'reaccion',
    // 'resolucion',
    // 'respuesta',
    // 'reconocimiento',
    // 'serie',
    // 'ensalada',
    // 'sesion',
    // 'hermana',
    // 'alumno',
    // 'supermercado',
    // 'seguridad',
    // 'sopa',
    // 'satisfaccion',
    // 'situacion',
    // 'sociedad',
    // 'significado',
    // 'habilidad',
    // 'secretaria',
    // 'orador',
    // 'camisa',
    // 'extraño',
    // 'solucion',
    // 'escena',
    // 'compras',
    // 'sistema',
    // 'muestra',
    // 'cantante',
    // 'ciencia',
    // 'almacenamiento',
    // 'signatura',
    // 'sugerencia',
    // 'discurso',
    // 'compasion',
    // 'seleccion',
    // 'estudio',
    // 'cancion',
    // 'declaracion',
    // 'sector',
    // 'cirugia',
    // 'relato',
    // 'configuracion',
    // 'exito',
    // 'filete',
    // 'estrategia',
    // 'cosa',
    // 'transporte',
    // 'tema',
    // 'teoria',
    // 'verdad',
    // 'television',
    // 'maestro',
    // 'tecnologia',
    // 'tension',
    // 'tenis',
    // 'lengua',
    // 'temperatura',
    // 'gracias',
    // 'cuento',
    // 'ciudad',
    // 'diente',
    // 'pensamiento',
    // 'garganta',
    // 'tradicion',
    // 'entrenador',
    // 'enseñanza',
    // 'esposa',
    // 'obrero',
    // 'semana',
    // 'mujer',
    // 'ganador',
    // 'debilidad',
    // 'riqueza',
    // 'escritura',
    // 'advertencia',
    // 'boda',
    // 'mundo',
    // 'madera',
    // 'escritor',
    // 'año',
    // 'juventud',
];